import Link from 'next/link';
import {getContext} from '@/data/finance';
import {signOut} from '@/app/auth-actions';
import {SupportForm} from '@/components/support-form';
import {Button} from '@/components/ui/button';
export default async function Profile(){
 const c=await getContext(false);const [{data:subscriptions},{data:requests}]=await Promise.all([c.db.from('subscriptions').select('id,provider,plan,status,purchased_at,renewal_at').eq('user_id',c.user.id),c.db.from('support_requests').select('id,subject,status,created_at').eq('user_id',c.user.id).order('created_at',{ascending:false}).limit(10)]);
 return <><header className="page-heading"><p className="eyebrow">TU CUENTA</p><h1>{c.profile.name}</h1><p>{c.user.email}</p></header><dl className="metric-grid"><div><dt>País</dt><dd>{c.profile.country}</dd></div><div><dt>Moneda</dt><dd>{c.profile.currency}</dd></div></dl><section className="section"><h2>Facturación</h2>{subscriptions?.length?subscriptions.map(s=><article key={s.id}><h3>{s.plan}</h3><p>Proveedor: {s.provider} · Estado: {s.status}</p><p>Compra: {s.purchased_at??'No disponible'}<br/>Renovación: {s.renewal_at??'No disponible'}</p><Button asChild variant="outline"><a href="https://consumer.hotmart.com/" target="_blank" rel="noopener noreferrer">Cancelar suscripción</a></Button><p className="hint">Administra la cancelación y consulta la fecha de acceso en el portal del proveedor.</p></article>):<p>No hay una suscripción registrada. Si ya compraste, solicita ayuda.</p>}<Link href="#soporte">Solicitar ayuda →</Link></section><section className="section" id="soporte"><h2>Soporte</h2><SupportForm/>{requests?.map(r=><p key={r.id}>{r.subject} · {r.status==='OPEN'?'Recibida':r.status}</p>)}</section><section className="section"><form action={signOut}><Button variant="outline">Cerrar sesión</Button></form></section></>;
}
