import Link from 'next/link';
import {decimalString,money} from '@/domain/money';
import {getContext,localMonth,getTransactions,getCategories} from '@/data/finance';
import {getPlan} from '@/data/plan';
import {totals,budgetStatus,progressValue,byCategory} from '@/domain/finance';
import {displayMoney} from '@/i18n/es';
import {budgetStatusText,common,languageFromLocale} from '@/i18n/app';
import {PlanForm} from '@/components/plan-form';
import {CategoryBudgetForm} from '@/components/category-budget-form';
import {PrincipleCard} from '@/components/principle-card';

type View='presupuesto'|'metas'|'deudas'|'ahorro';
const copy={
 es:{eyebrow:'DECISIONES CON INTENCIÓN',title:'Tu plan',intro:'Pequeños pasos para lo que de verdad importa.',nav:'Secciones del plan',guide:'GUÍA PARA ESTA DECISIÓN',spent:'Gastos registrados este mes',budget:'Presupuesto activo',debts:'Deudas registradas',goals:'Metas activas',noBudget:'Sin presupuesto',budgetUse:'Uso del presupuesto',used:'usados de',budgetHint:'Crea un presupuesto para ver el avance del mes.',categoryChart:'Gastos por categoría',categoryHint:'Registra movimientos para ver categorías reales.',goalProgress:'Progreso de metas',goalHint:'Crea una meta para ver el progreso.',debtChart:'Composición de deudas',debtHint:'Registra deudas si quieres acompañarlas aquí.',balance:'Saldo',monthlyPayment:'Pago mensual',due:'Vencimiento',updateGoal:'Actualizar meta',updateDebt:'Actualizar saldo y condiciones',debtUpdateHint:'Actualiza el saldo pendiente. Esto no crea un movimiento de pago.',reserveTitle:'Tu reserva inicial',reserveHint:'Una reserva empieza pequeña y crece con constancia. No fuerces ahorro si faltan necesidades básicas.',reserveLink:'Define una meta para tu reserva ->',defineBudget:'Define tu presupuesto',createGoal:'Crea una meta',registerDebt:'Registra una deuda',categoryLimits:'Límites por categoría'},
 pt:{eyebrow:'DECISÕES COM INTENÇÃO',title:'Seu plano',intro:'Pequenos passos para o que realmente importa.',nav:'Seções do plano',guide:'GUIA PARA ESTA DECISÃO',spent:'Gastos registrados este mês',budget:'Orçamento ativo',debts:'Dívidas registradas',goals:'Metas ativas',noBudget:'Sem orçamento',budgetUse:'Uso do orçamento',used:'usados de',budgetHint:'Crie um orçamento para ver o avanço do mês.',categoryChart:'Gastos por categoria',categoryHint:'Registre movimentos para ver categorias reais.',goalProgress:'Progresso das metas',goalHint:'Crie uma meta para ver o progresso.',debtChart:'Composição das dívidas',debtHint:'Registre dívidas se quiser acompanhá-las aqui.',balance:'Saldo',monthlyPayment:'Pagamento mensal',due:'Vencimento',updateGoal:'Atualizar meta',updateDebt:'Atualizar saldo e condições',debtUpdateHint:'Atualize o saldo pendente. Isso não cria um movimento de pagamento.',reserveTitle:'Sua reserva inicial',reserveHint:'Uma reserva começa pequena e cresce com constância. Não force economia se faltam necessidades básicas.',reserveLink:'Defina uma meta para sua reserva ->',defineBudget:'Defina seu orçamento',createGoal:'Crie uma meta',registerDebt:'Registre uma dívida',categoryLimits:'Limites por categoria'}
};
const viewCopy={
 es:{presupuesto:{label:'Presupuesto',theme:'planificación',title:'Construye un límite antes de que el mes decida por ti.',description:'Un presupuesto no controla tu vida; te ayuda a administrar con intención lo que Dios puso en tus manos.',action:'Define un límite mensual realista y luego reparte las categorías que más pesan.'},metas:{label:'Metas',theme:'sabiduría',title:'Convierte tus deseos en pasos visibles.',description:'Una meta clara ayuda a comparar recursos, tiempo y prioridades antes de comprometer dinero.',action:'Elige una meta pequeña y registra cuánto ya tienes separado.'},deudas:{label:'Deudas',theme:'deuda',title:'Mira tus deudas con verdad y esperanza.',description:'Registrar una deuda no es vergüenza; es el primer paso para recuperar margen y libertad de decisión.',action:'Empieza por el saldo y el pago mensual de una deuda concreta.'},ahorro:{label:'Ahorro',theme:'ahorro',title:'Tu reserva protege decisiones futuras.',description:'Ahorrar según tus posibilidades crea espacio para actuar con más paz ante imprevistos.',action:'Si todavía no tienes meta de reserva, crea una meta sencilla para comenzar.'}},
 pt:{presupuesto:{label:'Orçamento',theme:'planificación',title:'Construa um limite antes que o mês decida por você.',description:'Um orçamento não controla sua vida; ajuda você a administrar com intenção o que Deus colocou em suas mãos.',action:'Defina um limite mensal realista e depois distribua as categorias que mais pesam.'},metas:{label:'Metas',theme:'sabiduría',title:'Transforme seus desejos em passos visíveis.',description:'Uma meta clara ajuda a comparar recursos, tempo e prioridades antes de comprometer dinheiro.',action:'Escolha uma meta pequena e registre quanto você já separou.'},deudas:{label:'Dívidas',theme:'deuda',title:'Olhe suas dívidas com verdade e esperança.',description:'Registrar uma dívida não é vergonha; é o primeiro passo para recuperar margem e liberdade de decisão.',action:'Comece pelo saldo e pagamento mensal de uma dívida concreta.'},ahorro:{label:'Reserva',theme:'ahorro',title:'Sua reserva protege decisões futuras.',description:'Economizar conforme suas possibilidades cria espaço para agir com mais paz diante de imprevistos.',action:'Se ainda não tem meta de reserva, crie uma meta simples para começar.'}}
};

function normalizeView(value:string|undefined):View{return value==='metas'||value==='deudas'||value==='ahorro'?value:'presupuesto';}
function pct(value:bigint,total:bigint){if(total<=0n)return 0;const result=Number(value*100n/total);return Math.max(0,Math.min(100,result));}
function width(value:number){return {width:`${Math.max(2,Math.min(100,value))}%`};}

export default async function Plan({searchParams}:{searchParams:Promise<{vista?:string}>}){
 const c=await getContext(),month=localMonth(c.profile.timezone);const query=await searchParams;const lang=languageFromLocale(c.profile.locale);const t=copy[lang];const views=viewCopy[lang];const ui=common(c.profile.locale);
 const view=normalizeView(query.vista),meta=views[view];
 const [plan,transactions,categories,principleResult]=await Promise.all([getPlan(c),getTransactions(c,month),getCategories(c),c.db.from('biblical_principles').select('reference,principle,application,risk_context').eq('theme',meta.theme).eq('active',true).single()]);const format=(value:string|bigint,currency:string)=>displayMoney(value.toString(),currency,c.profile.locale);
 const decimal=(value:string,currency:string)=>decimalString(money(BigInt(value),currency));
 const monthlyTotals=totals(transactions,c.profile.currency),spent=BigInt(monthlyTotals.expenses.amountMinor);
 const currentBudget=plan.budgets.find(b=>b.month.startsWith(month)&&b.currency===c.profile.currency),categorySpending=byCategory(transactions,c.profile.currency);
 const totalDebt=plan.debts.filter(d=>d.currency===c.profile.currency).reduce((sum,d)=>sum+BigInt(d.balance_minor),0n);
 const activeGoals=plan.goals.filter(g=>g.currency===c.profile.currency).length;
 const topCategories=Object.entries(categorySpending).map(([id,amount])=>({id,name:categories.find(cat=>cat.id===id)?.name??ui.category,amount:BigInt(amount)})).sort((a,b)=>a.amount>b.amount?-1:1).slice(0,6);
 const topCategoryMax=topCategories[0]?.amount??0n;
 const goals=plan.goals.filter(g=>g.currency===c.profile.currency);
 const debts=plan.debts.filter(d=>d.currency===c.profile.currency);
 const budgetAmount=currentBudget?BigInt(currentBudget.amount_minor):0n,budgetPercent=pct(spent,budgetAmount);
 return <><header className="page-heading"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p>{t.intro}</p></header><nav className="subnav" aria-label={t.nav}>{(Object.keys(views) as View[]).map(id=><Link key={id} aria-current={view===id?'page':undefined} href={'/plan?vista='+id}>{views[id].label}</Link>)}</nav>
 <section className="plan-guidance"><div><p className="eyebrow">{t.guide}</p><h2>{meta.title}</h2><p>{meta.description}</p><strong>{meta.action}</strong></div>{principleResult.data&&<PrincipleCard reference={principleResult.data.reference} principle={principleResult.data.principle} application={principleResult.data.application} riskContext={principleResult.data.risk_context}/>}</section>
 <dl className="metric-grid plan-summary"><div><dt>{t.spent}</dt><dd>{format(spent,c.profile.currency)}</dd></div><div><dt>{t.budget}</dt><dd>{currentBudget?format(currentBudget.amount_minor,currentBudget.currency):t.noBudget}</dd></div><div><dt>{t.debts}</dt><dd>{format(totalDebt,c.profile.currency)}</dd></div><div><dt>{t.goals}</dt><dd>{activeGoals.toString()}</dd></div></dl>
 <section className="section plan-charts"><div className="chart-card"><h2>{t.budgetUse}</h2>{currentBudget?<><div className="chart-bar"><i style={width(budgetPercent)} data-alert={budgetPercent>100||undefined}/></div><p>{format(spent,c.profile.currency)} {t.used} {format(budgetAmount,c.profile.currency)} · {budgetStatusText(budgetStatus(spent,budgetAmount).status,c.profile.locale)}</p></>:<p className="hint">{t.budgetHint}</p>}</div><div className="chart-card"><h2>{t.categoryChart}</h2>{topCategories.length?<div className="bar-list">{topCategories.map(item=><div key={item.id}><span>{item.name}</span><div className="chart-bar"><i style={width(pct(item.amount,topCategoryMax))}/></div><strong>{format(item.amount,c.profile.currency)}</strong></div>)}</div>:<p className="hint">{t.categoryHint}</p>}</div><div className="chart-card"><h2>{t.goalProgress}</h2>{goals.length?<div className="bar-list">{goals.slice(0,5).map(goal=><div key={goal.id}><span>{goal.name}</span><div className="chart-bar"><i style={width(progressValue(goal.current_amount_minor,goal.target_amount_minor)/100)}/></div><strong>{format(goal.current_amount_minor,goal.currency)} / {format(goal.target_amount_minor,goal.currency)}</strong></div>)}</div>:<p className="hint">{t.goalHint}</p>}</div><div className="chart-card"><h2>{t.debtChart}</h2>{debts.length?<div className="bar-list">{debts.slice(0,5).map(debt=><div key={debt.id}><span>{debt.name}</span><div className="chart-bar"><i style={width(pct(BigInt(debt.balance_minor),totalDebt))}/></div><strong>{format(debt.balance_minor,debt.currency)}</strong></div>)}</div>:<p className="hint">{t.debtHint}</p>}</div></section>
 <div className="plan-list">{view==='presupuesto'&&plan.budgets.map(b=><article className="plan-item" key={b.id}><h3>{b.month.slice(0,7)} · {format(b.amount_minor,b.currency)}</h3>{b.month.startsWith(month)&&b.currency===c.profile.currency&&<p>{budgetStatusText(budgetStatus(spent,BigInt(b.amount_minor)).status,c.profile.locale)} · {t.spent}: {format(spent,b.currency)}</p>}</article>)}
 {(view==='metas'||view==='ahorro')&&plan.goals.map(g=><article className="plan-item" key={g.id}><h3>{g.name}</h3><p>{format(g.current_amount_minor,g.currency)} / {format(g.target_amount_minor,g.currency)}</p><progress aria-label={'Progresso '+g.name} max={10000} value={progressValue(g.current_amount_minor,g.target_amount_minor)}/>{g.target_date&&<small>{g.target_date}</small>}<details><summary>{t.updateGoal}</summary><PlanForm kind="goal" currency={g.currency} month={month} locale={c.profile.locale} initial={{id:g.id,name:g.name,amount:decimal(g.target_amount_minor,g.currency),current:decimal(g.current_amount_minor,g.currency),date:g.target_date??'',interest:''}}/></details></article>)}
 {view==='deudas'&&plan.debts.map(d=><article className="plan-item" key={d.id}><h3>{d.name}</h3><p>{t.balance}: {format(d.balance_minor,d.currency)}<br/>{t.monthlyPayment}: {format(d.monthly_payment_minor,d.currency)}</p>{d.due_date&&<small>{t.due}: {d.due_date}</small>}<details><summary>{t.updateDebt}</summary><p className="hint">{t.debtUpdateHint}</p><PlanForm kind="debt" currency={d.currency} month={month} locale={c.profile.locale} initial={{id:d.id,name:d.name,amount:decimal(d.balance_minor,d.currency),current:decimal(d.monthly_payment_minor,d.currency),date:d.due_date??'',interest:d.interest_rate_basis_points===null?'':decimal(String(d.interest_rate_basis_points),'USD')}}/></details></article>)}</div>
 <section className="section">{view==='ahorro'?<><h2>{t.reserveTitle}</h2><p>{format(c.profile.reserve_minor,c.profile.currency)}</p><p className="hint">{t.reserveHint}</p><Link href="/plan?vista=metas">{t.reserveLink}</Link></>:<><h2>{view==='presupuesto'?t.defineBudget:view==='metas'?t.createGoal:t.registerDebt}</h2><PlanForm key={view} kind={view==='presupuesto'?'budget':view==='metas'?'goal':'debt'} currency={c.profile.currency} month={month} locale={c.profile.locale}/></>}</section>
 {view==='presupuesto'&&currentBudget&&<section className="section"><h2>{t.categoryLimits} · {month}</h2>{plan.budgetCategories.filter(b=>b.budget_id===currentBudget.id).map(b=><p key={b.id}>{categories.find(cat=>cat.id===b.category_id)?.name}: {format(categorySpending[b.category_id]??'0',c.profile.currency)} / {format(b.amount_minor,c.profile.currency)} · {budgetStatusText(budgetStatus(BigInt(categorySpending[b.category_id]??'0'),BigInt(b.amount_minor)).status,c.profile.locale)}</p>)}<CategoryBudgetForm budgetId={currentBudget.id} categories={categories} currency={c.profile.currency} locale={c.profile.locale}/></section>}</>;
}