import Link from 'next/link';
import {decimalString,money} from '@/domain/money';
import {getContext,localMonth,getTransactions,getCategories} from '@/data/finance';
import {getPlan} from '@/data/plan';
import {totals,budgetStatus,progressValue,byCategory} from '@/domain/finance';
import {displayMoney} from '@/i18n/es';
import {PlanForm} from '@/components/plan-form';
import {CategoryBudgetForm} from '@/components/category-budget-form';
export default async function Plan({searchParams}:{searchParams:Promise<{vista?:string}>}){
 const c=await getContext(),month=localMonth(c.profile.timezone);const query=await searchParams;
 const view=['metas','deudas','ahorro'].includes(query.vista??'')?query.vista!:'presupuesto';
 const [plan,transactions,categories]=await Promise.all([getPlan(c),getTransactions(c,month),getCategories(c)]);const format=(value:string,currency:string)=>displayMoney(value,currency,c.profile.locale);
 const decimal=(value:string,currency:string)=>decimalString(money(BigInt(value),currency));
 const spent=totals(transactions,c.profile.currency).expenses.amountMinor;
 const currentBudget=plan.budgets.find(b=>b.month.startsWith(month)&&b.currency===c.profile.currency),categorySpending=byCategory(transactions,c.profile.currency);
 return <><header className="page-heading"><p className="eyebrow">DECISIONES CON INTENCIÓN</p><h1>Tu plan</h1><p>Pequeños pasos para lo que de verdad importa.</p></header><nav className="subnav" aria-label="Secciones del plan">{[['presupuesto','Presupuesto'],['metas','Metas'],['deudas','Deudas'],['ahorro','Ahorro']].map(([id,label])=><Link key={id} aria-current={view===id?'page':undefined} href={'/plan?vista='+id}>{label}</Link>)}</nav>
 <div className="plan-list">{view==='presupuesto'&&plan.budgets.map(b=><article className="plan-item" key={b.id}><h3>{b.month.slice(0,7)} · {format(b.amount_minor,b.currency)}</h3>{b.month.startsWith(month)&&b.currency===c.profile.currency&&<p>{budgetStatus(BigInt(spent),BigInt(b.amount_minor)).status} · Gastado: {format(spent,b.currency)}</p>}</article>)}
 {(view==='metas'||view==='ahorro')&&plan.goals.map(g=><article className="plan-item" key={g.id}><h3>{g.name}</h3><p>{format(g.current_amount_minor,g.currency)} de {format(g.target_amount_minor,g.currency)}</p><progress aria-label={'Progreso de '+g.name} max={10000} value={progressValue(g.current_amount_minor,g.target_amount_minor)}/>{g.target_date&&<small>Objetivo: {g.target_date}</small>}<details><summary>Actualizar meta</summary><PlanForm kind="goal" currency={g.currency} month={month} initial={{id:g.id,name:g.name,amount:decimal(g.target_amount_minor,g.currency),current:decimal(g.current_amount_minor,g.currency),date:g.target_date??'',interest:''}}/></details></article>)}
 {view==='deudas'&&plan.debts.map(d=><article className="plan-item" key={d.id}><h3>{d.name}</h3><p>Saldo: {format(d.balance_minor,d.currency)}<br/>Pago mensual: {format(d.monthly_payment_minor,d.currency)}</p>{d.due_date&&<small>Vencimiento: {d.due_date}</small>}<details><summary>Actualizar saldo y condiciones</summary><p className="hint">Actualiza el saldo pendiente. Esto no crea un movimiento de pago.</p><PlanForm kind="debt" currency={d.currency} month={month} initial={{id:d.id,name:d.name,amount:decimal(d.balance_minor,d.currency),current:decimal(d.monthly_payment_minor,d.currency),date:d.due_date??'',interest:d.interest_rate_basis_points===null?'':decimal(String(d.interest_rate_basis_points),'USD')}}/></details></article>)}</div>
 <section className="section">{view==='ahorro'?<><h2>Tu reserva inicial</h2><p>{format(c.profile.reserve_minor,c.profile.currency)} · Estimación del onboarding.</p><Link href="/plan?vista=metas">Define una meta para tu reserva →</Link></>:<><h2>{view==='presupuesto'?'Define tu presupuesto':view==='metas'?'Crea una meta':'Registra una deuda'}</h2><PlanForm key={view} kind={view==='presupuesto'?'budget':view==='metas'?'goal':'debt'} currency={c.profile.currency} month={month}/></>}</section>
 {view==='presupuesto'&&currentBudget&&<section className="section"><h2>Límites por categoría · {month}</h2>{plan.budgetCategories.filter(b=>b.budget_id===currentBudget.id).map(b=><p key={b.id}>{categories.find(cat=>cat.id===b.category_id)?.name}: {format(categorySpending[b.category_id]??'0',c.profile.currency)} de {format(b.amount_minor,c.profile.currency)} · {budgetStatus(BigInt(categorySpending[b.category_id]??'0'),BigInt(b.amount_minor)).status}</p>)}<CategoryBudgetForm budgetId={currentBudget.id} categories={categories} currency={c.profile.currency}/></section>}</>;
}
