import Link from 'next/link';
import {getContext,getTransactions,getCategories,localMonth} from '@/data/finance';
import {displayMoney} from '@/i18n/es';
import {Button} from '@/components/ui/button';
export default async function Transactions({searchParams}:{searchParams:Promise<{mes?:string;q?:string;categoria?:string;tipo?:string;cuenta?:string}>}){
 const c=await getContext();const query=await searchParams;const month=query.mes&&/^\d{4}-(0[1-9]|1[0-2])$/.test(query.mes)?query.mes:localMonth(c.profile.timezone);
 const [rows,categories]=await Promise.all([getTransactions(c,month),getCategories(c)]);const categoryNames=new Map(categories.map(x=>[x.id,x.name]));
 const filtered=rows.filter(t=>(!query.q||(t.description+' '+t.merchant).toLowerCase().includes(query.q.toLowerCase()))&&(!query.categoria||t.categoryId===query.categoria)&&(!query.tipo||t.kind===query.tipo)&&(!query.cuenta||t.accountId===query.cuenta));
 return <><header className="page-heading"><p className="eyebrow">CADA MOVIMIENTO CUENTA</p><h1>Movimientos</h1><p>Conoce la historia detrás de tus números.</p></header><div className="page-actions"><Button asChild><Link href="/movimientos/nuevo">Registrar movimiento</Link></Button><Button asChild variant="outline"><Link href="/importar">Subir extracto</Link></Button></div>
 <form className="filters"><div><label htmlFor="q">Buscar</label><input id="q" name="q" defaultValue={query.q} placeholder="Descripción o comercio"/></div><div><label htmlFor="mes">Mes</label><input id="mes" name="mes" type="month" defaultValue={month}/></div><div><label htmlFor="categoria">Categoría</label><select id="categoria" name="categoria" defaultValue={query.categoria??''}><option value="">Todas</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><label htmlFor="tipo">Tipo</label><select id="tipo" name="tipo" defaultValue={query.tipo??''}><option value="">Todos</option><option value="INCOME">Ingresos</option><option value="EXPENSE">Gastos</option></select></div><Button type="submit" variant="outline">Filtrar</Button></form>
 {!filtered.length?<section className="empty"><h2>Aún no hay movimientos aquí.</h2><p>Registra un movimiento o revisa los filtros.</p></section>:<ul className="transaction-list">{filtered.map(t=><li key={t.id}><div><p>{t.description}</p><small>{t.merchant} · {categoryNames.get(t.categoryId)}<br/>{t.occurredAt} · {({MANUAL:'Manual',IMPORT:'Importación',WHATSAPP:'WhatsApp',BANK:'Banco',RECEIPT:'Recibo'} as Record<string,string>)[t.source]}</small><div className="row-actions"><Link href={'/movimientos/'+t.id}>Editar o eliminar</Link></div></div><span className="amount">{t.kind==='EXPENSE'?'−':'+'}{displayMoney(t.amountMinor,t.currency,c.profile.locale)}</span></li>)}</ul>}</>;
}
