import Link from 'next/link';
import {getContext,getTransactions,getCategories,localMonth} from '@/data/finance';
import {displayMoney} from '@/i18n/es';
import {Button} from '@/components/ui/button';
import {PrincipleCard} from '@/components/principle-card';
export default async function Transactions({searchParams}:{searchParams:Promise<{mes?:string;q?:string;categoria?:string;tipo?:string;cuenta?:string;guardado?:string}>}){
 const c=await getContext();const query=await searchParams;const month=query.mes&&/^\d{4}-(0[1-9]|1[0-2])$/.test(query.mes)?query.mes:localMonth(c.profile.timezone);
 const [rows,categories,principleResult]=await Promise.all([getTransactions(c,month),getCategories(c),c.db.from('biblical_principles').select('reference,principle,application,risk_context').eq('theme','responsabilidad').eq('active',true).single()]);const categoryNames=new Map(categories.map(x=>[x.id,x.name]));
 const filtered=rows.filter(t=>(!query.q||(t.description+' '+t.merchant).toLowerCase().includes(query.q.toLowerCase()))&&(!query.categoria||t.categoryId===query.categoria)&&(!query.tipo||t.kind===query.tipo)&&(!query.cuenta||t.accountId===query.cuenta));
 const savedMessage=query.guardado==='creado'?'Movimiento registrado. La claridad crece con cada registro.':query.guardado==='actualizado'?'Movimiento actualizado. Tus datos quedan más claros.':query.guardado==='eliminado'?'Movimiento eliminado. Revisa tu panorama con calma.':'';
 return <><header className="page-heading"><p className="eyebrow">CADA MOVIMIENTO CUENTA</p><h1>Movimientos</h1><p>Conoce la historia detrás de tus números.</p></header>{savedMessage&&<p role="status" className="success-message">{savedMessage}</p>}<div className="page-actions"><Button asChild><Link href="/movimientos/nuevo">Registrar movimiento</Link></Button><Button asChild variant="outline"><Link href="/importar">Subir extracto</Link></Button></div>
 <section className="movement-guidance">{principleResult.data&&<PrincipleCard reference={principleResult.data.reference} principle={principleResult.data.principle} application={principleResult.data.application} riskContext={principleResult.data.risk_context}/>}<div><h2>Una práctica pequeña con fruto grande.</h2><p>Registrar movimientos no es vivir con miedo al dinero. Es mirar con honestidad para decidir con sabiduría.</p></div></section>
 <form className="filters"><div><label htmlFor="q">Buscar</label><input id="q" name="q" defaultValue={query.q} placeholder="Descripción o comercio"/></div><div><label htmlFor="mes">Mes</label><input id="mes" name="mes" type="month" defaultValue={month}/></div><div><label htmlFor="categoria">Categoría</label><select id="categoria" name="categoria" defaultValue={query.categoria??''}><option value="">Todas</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><label htmlFor="tipo">Tipo</label><select id="tipo" name="tipo" defaultValue={query.tipo??''}><option value="">Todos</option><option value="INCOME">Ingresos</option><option value="EXPENSE">Gastos</option></select></div><Button type="submit" variant="outline">Filtrar</Button></form>
 {!filtered.length?<section className="empty"><h2>Aún no hay movimientos aquí.</h2><p>{rows.length?'Prueba limpiar filtros para volver a ver tus registros.':'Registra tu primer movimiento. La claridad empieza con un solo dato fiel.'}</p><Button asChild><Link href="/movimientos/nuevo">Registrar mi primer movimiento</Link></Button></section>:<ul className="transaction-list">{filtered.map(t=><li key={t.id}><div><p>{t.description}</p><small>{t.merchant||'Sin comercio'} · {categoryNames.get(t.categoryId)}<br/>{t.occurredAt} · {({MANUAL:'Manual',IMPORT:'Importación',WHATSAPP:'WhatsApp',BANK:'Banco',RECEIPT:'Recibo'} as Record<string,string>)[t.source]}</small><div className="row-actions"><Link href={'/movimientos/'+t.id}>Editar o eliminar</Link></div></div><span className="amount">{t.kind==='EXPENSE'?'−':'+'}{displayMoney(t.amountMinor,t.currency,c.profile.locale)}</span></li>)}</ul>}</>;
}
