import Link from 'next/link';
import {getContext,getTransactions,getCategories,localMonth} from '@/data/finance';
import {displayMoney} from '@/i18n/es';
import {common,languageFromLocale,transactionSourceText} from '@/i18n/app';
import {Button} from '@/components/ui/button';
import {PrincipleCard} from '@/components/principle-card';

const copy={
 es:{eyebrow:'CADA MOVIMIENTO CUENTA',title:'Movimientos',intro:'Conoce la historia detrás de tus números.',created:'Movimiento registrado. La claridad crece con cada registro.',updated:'Movimiento actualizado. Tus datos quedan más claros.',deleted:'Movimiento eliminado. Revisa tu panorama con calma.',new:'Registrar movimiento',import:'Subir extracto',guidanceTitle:'Una práctica pequeña con fruto grande.',guidanceText:'Registrar movimientos no es vivir con miedo al dinero. Es mirar con honestidad para decidir con sabiduría.',searchPlaceholder:'Descripción o comercio',emptyTitle:'Aún no hay movimientos aquí.',emptyFiltered:'Prueba limpiar filtros para volver a ver tus registros.',emptyStart:'Registra tu primer movimiento. La claridad empieza con un solo dato fiel.',first:'Registrar mi primer movimiento',noMerchant:'Sin comercio'},
 pt:{eyebrow:'CADA MOVIMENTO CONTA',title:'Movimentos',intro:'Conheça a história por trás dos seus números.',created:'Movimento registrado. A clareza cresce a cada registro.',updated:'Movimento atualizado. Seus dados ficaram mais claros.',deleted:'Movimento excluído. Revise seu panorama com calma.',new:'Registrar movimento',import:'Subir extrato',guidanceTitle:'Uma prática pequena com fruto grande.',guidanceText:'Registrar movimentos não é viver com medo do dinheiro. É olhar com honestidade para decidir com sabedoria.',searchPlaceholder:'Descrição ou comércio',emptyTitle:'Ainda não há movimentos aqui.',emptyFiltered:'Tente limpar os filtros para ver seus registros novamente.',emptyStart:'Registre seu primeiro movimento. A clareza começa com um único dado fiel.',first:'Registrar meu primeiro movimento',noMerchant:'Sem comércio'}
};

export default async function Transactions({searchParams}:{searchParams:Promise<{mes?:string;q?:string;categoria?:string;tipo?:string;cuenta?:string;guardado?:string}>}){
 const c=await getContext();const query=await searchParams;const month=query.mes&&/^\d{4}-(0[1-9]|1[0-2])$/.test(query.mes)?query.mes:localMonth(c.profile.timezone);const t=copy[languageFromLocale(c.profile.locale)];const ui=common(c.profile.locale);
 const [rows,categories,principleResult]=await Promise.all([getTransactions(c,month),getCategories(c),c.db.from('biblical_principles').select('reference,principle,application,risk_context').eq('theme','responsabilidad').eq('active',true).single()]);const categoryNames=new Map(categories.map(x=>[x.id,x.name]));
 const filtered=rows.filter(row=>(!query.q||(row.description+' '+row.merchant).toLowerCase().includes(query.q.toLowerCase()))&&(!query.categoria||row.categoryId===query.categoria)&&(!query.tipo||row.kind===query.tipo)&&(!query.cuenta||row.accountId===query.cuenta));
 const savedMessage=query.guardado==='creado'?t.created:query.guardado==='actualizado'?t.updated:query.guardado==='eliminado'?t.deleted:'';
 return <><header className="page-heading"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p>{t.intro}</p></header>{savedMessage&&<p role="status" className="success-message">{savedMessage}</p>}<div className="page-actions"><Button asChild><Link href="/movimientos/nuevo">{t.new}</Link></Button><Button asChild variant="outline"><Link href="/importar">{t.import}</Link></Button></div>
 <section className="movement-guidance">{principleResult.data&&<PrincipleCard reference={principleResult.data.reference} principle={principleResult.data.principle} application={principleResult.data.application} riskContext={principleResult.data.risk_context}/>}<div><h2>{t.guidanceTitle}</h2><p>{t.guidanceText}</p></div></section>
 <form className="filters"><div><label htmlFor="q">{ui.search}</label><input id="q" name="q" defaultValue={query.q} placeholder={t.searchPlaceholder}/></div><div><label htmlFor="mes">{ui.month}</label><input id="mes" name="mes" type="month" defaultValue={month}/></div><div><label htmlFor="categoria">{ui.category}</label><select id="categoria" name="categoria" defaultValue={query.categoria??''}><option value="">{ui.all}</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div><label htmlFor="tipo">{ui.type}</label><select id="tipo" name="tipo" defaultValue={query.tipo??''}><option value="">{ui.allMasc}</option><option value="INCOME">{ui.income}</option><option value="EXPENSE">{ui.expenses}</option></select></div><Button type="submit" variant="outline">{ui.filter}</Button></form>
 {!filtered.length?<section className="empty"><h2>{t.emptyTitle}</h2><p>{rows.length?t.emptyFiltered:t.emptyStart}</p><Button asChild><Link href="/movimientos/nuevo">{t.first}</Link></Button></section>:<ul className="transaction-list">{filtered.map(row=><li key={row.id}><div><p>{row.description}</p><small>{row.merchant||t.noMerchant} · {categoryNames.get(row.categoryId)}<br/>{row.occurredAt} · {transactionSourceText(row.source,c.profile.locale)}</small><div className="row-actions"><Link href={'/movimientos/'+row.id}>{ui.editOrDelete}</Link></div></div><span className="amount">{row.kind==='EXPENSE'?'−':'+'}{displayMoney(row.amountMinor,row.currency,c.profile.locale)}</span></li>)}</ul>}</>;
}