import Link from 'next/link';
import {getCategories,getContext,getTransactions,localMonth} from '@/data/finance';
import {byCategory,duplicates,totals} from '@/domain/finance';
import {displayMoney} from '@/i18n/es';
import {languageFromLocale} from '@/i18n/app';
import {Button} from '@/components/ui/button';
import {PrincipleCard} from '@/components/principle-card';
import {getInternalNotifications} from '@/data/notifications';
import {InternalNotifications} from '@/components/internal-notifications';

function chooseTodayPrinciple({hasRows,net,debt,reserve,objective}:{hasRows:boolean;net:bigint;debt:bigint;reserve:bigint;objective:string|null}){
 if(debt>0n||objective==='Salir de deudas')return 'deuda';
 if(reserve===0n||objective==='Crear una reserva')return 'ahorro';
 if(hasRows&&net<0n)return 'prudencia';
 if(objective==='Ser más fiel en la administración')return 'mayordomía';
 if(!hasRows)return 'responsabilidad';
 return 'sabiduría';
}

const copy={
 es:{eyebrow:'TU DINERO, CON PROPÓSITO',greeting:(name:string)=>`Buenos días, ${name}.`,intro:'Esto es lo que necesitas saber sobre tu dinero hoy.',balance:'Balance de movimientos del mes',balanceHint:'Ingresos registrados menos gastos registrados. No es tu saldo bancario.',income:'Ingresos del mes',expenses:'Gastos del mes',devotional:'DEVOCIONAL FINANCIERO DE HOY',practice:'Aplicación práctica',prayer:'Oración/reflexión opcional',devotionalNote:'Esto no es una promesa de resultado financiero ni una medida de fe. Es una guía para decidir con calma.',actionEyebrow:'UNA ACCIÓN PRUDENTE PARA HOY',topCategory:(category:string)=>`La categoría con más peso registrado este mes es ${category}.`,noPattern:'Todavía falta registrar movimientos para identificar patrones.',newMovement:'Registrar movimiento',import:'Subir extracto',start:'Tu punto de partida',startText:'Estimaciones que compartiste al comenzar.',available:'Disponible estimado mensual',reserve:'Reserva inicial',debt:'Deuda inicial',detected:'MAYORDOMO DETECTÓ',noRowsTitle:'Aún no conozco tus movimientos.',noRowsText:'Registra tu primer gasto y empezaré a ayudarte.',overTitle:'Tus gastos registrados superan tus ingresos.',okTitle:'Ya estás dando orden a tu dinero.',dupes:(count:number)=>`${count} posibles duplicidades merecen una revisión.`,continue:'Continúa registrando para tener una visión más completa.',report:'Ver Informe de Mayordomía →',actionNoRows:'Registra tu primer movimiento hoy. La claridad crece cuando lo pequeño también queda visible.',actionDupes:(count:number)=>`Revisa ${count} posible${count===1?' duplicidad':'s duplicidades'} antes de tomar decisiones con estos números.`,actionNet:(category?:string)=>`Haz una pausa antes de un nuevo gasto y revisa ${category??'tu categoría principal'} con prudencia.`,actionReserve:'Separa una cantidad pequeña y realista para tu reserva antes de aumentar gastos flexibles.',actionDebt:'Revisa cuál deuda necesita atención esta semana y evita asumir nuevos compromisos sin comparar tu margen.',actionDefault:(category?:string)=>`Observa ${category??'tu categoría principal'} y decide un límite sencillo para las próximas 24 horas.`},
 pt:{eyebrow:'SEU DINHEIRO, COM PROPÓSITO',greeting:(name:string)=>`Bom dia, ${name}.`,intro:'Isto é o que você precisa saber sobre seu dinheiro hoje.',balance:'Balanço dos movimentos do mês',balanceHint:'Receitas registradas menos gastos registrados. Não é seu saldo bancário.',income:'Receitas do mês',expenses:'Gastos do mês',devotional:'DEVOCIONAL FINANCEIRO DE HOJE',practice:'Aplicação prática',prayer:'Oração/reflexão opcional',devotionalNote:'Isto não é promessa de resultado financeiro nem medida de fé. É um guia para decidir com calma.',actionEyebrow:'UMA AÇÃO PRUDENTE PARA HOJE',topCategory:(category:string)=>`A categoria com mais peso registrado este mês é ${category}.`,noPattern:'Ainda faltam movimentos para identificar padrões.',newMovement:'Registrar movimento',import:'Subir extrato',start:'Seu ponto de partida',startText:'Estimativas que você compartilhou ao começar.',available:'Disponível mensal estimado',reserve:'Reserva inicial',debt:'Dívida inicial',detected:'MAYORDOMO DETECTOU',noRowsTitle:'Ainda não conheço seus movimentos.',noRowsText:'Registre seu primeiro gasto e começarei a ajudar.',overTitle:'Seus gastos registrados superam suas receitas.',okTitle:'Você já está dando ordem ao seu dinheiro.',dupes:(count:number)=>`${count} possíveis duplicidades merecem revisão.`,continue:'Continue registrando para ter uma visão mais completa.',report:'Ver Relatório de Mordomia →',actionNoRows:'Registre seu primeiro movimento hoje. A clareza cresce quando o pequeno também fica visível.',actionDupes:(count:number)=>`Revise ${count} possível(is) duplicidade(s) antes de tomar decisões com estes números.`,actionNet:(category?:string)=>`Faça uma pausa antes de um novo gasto e revise ${category??'sua categoria principal'} com prudência.`,actionReserve:'Separe uma quantia pequena e realista para sua reserva antes de aumentar gastos flexíveis.',actionDebt:'Revise qual dívida precisa de atenção esta semana e evite assumir novos compromissos sem comparar sua margem.',actionDefault:(category?:string)=>`Observe ${category??'sua categoria principal'} e defina um limite simples para as próximas 24 horas.`}
};

function todayAction({hasRows,net,topCategory,duplicatesCount,objective,locale}:{hasRows:boolean;net:bigint;topCategory?:string;duplicatesCount:number;objective:string|null;locale:string}){
 const t=copy[languageFromLocale(locale)];
 if(!hasRows)return t.actionNoRows;
 if(duplicatesCount>0)return t.actionDupes(duplicatesCount);
 if(net<0n)return t.actionNet(topCategory);
 if(objective==='Crear una reserva')return t.actionReserve;
 if(objective==='Salir de deudas')return t.actionDebt;
 return t.actionDefault(topCategory);
}

function devotional(theme:string,application:string,locale:string){
 const lang=languageFromLocale(locale);
 const reflections={
  es:{deuda:{title:'Libertad para decidir con calma',reflection:'La deuda puede reducir margen y tranquilidad. Mirarla de frente es un acto de prudencia, no de vergüenza.',practice:'Elige una deuda y confirma saldo, pago mínimo y fecha de vencimiento.',prayer:'Señor, ayúdame a decidir con claridad, paciencia y responsabilidad.'},ahorro:{title:'Preparar sin ansiedad',reflection:'Guardar recursos cuando es posible puede proteger a tu familia y darte margen para servir mejor.',practice:'Define una cantidad pequeña que puedas separar sin descuidar necesidades básicas.',prayer:'Dame sabiduría para cuidar lo que recibo y paz para avanzar paso a paso.'},prudencia:{title:'Pausar antes de actuar',reflection:'La prudencia no paraliza; abre espacio para decidir con información y dominio propio.',practice:'Antes de un gasto no esencial, espera 10 minutos y revisa tu categoría principal.',prayer:'Guíame a reconocer riesgos sin miedo y a actuar con templanza.'},mayordomía:{title:'Administrar con propósito',reflection:'La mayordomía conecta tus recursos con tus valores, tu familia y tu servicio.',practice:'Elige una decisión financiera de hoy y relaciónala con el propósito que declaraste.',prayer:'Enséñame a administrar con fidelidad, humildad y amor.'},responsabilidad:{title:'Fidelidad en lo pequeño',reflection:'Un registro pequeño también cuenta. La claridad se construye con hábitos sencillos.',practice:'Registra el próximo movimiento que recuerdes, aunque sea pequeño.',prayer:'Ayúdame a ser fiel en lo pequeño sin cargar culpa ni perfeccionismo.'},sabiduría:{title:'Buscar sabiduría antes de decidir',reflection:'La sabiduría crece cuando observas, comparas y decides con calma.',practice:application||'Revisa tus números antes de tomar la siguiente decisión financiera.',prayer:'Dame sabiduría para usar bien mis recursos y servir con libertad.'}},
  pt:{deuda:{title:'Liberdade para decidir com calma',reflection:'A dívida pode reduzir margem e tranquilidade. Olhar para ela de frente é prudência, não vergonha.',practice:'Escolha uma dívida e confirme saldo, pagamento mínimo e vencimento.',prayer:'Senhor, ajuda-me a decidir com clareza, paciência e responsabilidade.'},ahorro:{title:'Preparar sem ansiedade',reflection:'Guardar recursos quando possível pode proteger sua família e dar margem para servir melhor.',practice:'Defina uma quantia pequena que possa separar sem descuidar necessidades básicas.',prayer:'Dá-me sabedoria para cuidar do que recebo e paz para avançar passo a passo.'},prudencia:{title:'Pausar antes de agir',reflection:'A prudência não paralisa; abre espaço para decidir com informação e domínio próprio.',practice:'Antes de um gasto não essencial, espere 10 minutos e revise sua categoria principal.',prayer:'Guia-me para reconhecer riscos sem medo e agir com temperança.'},mayordomía:{title:'Administrar com propósito',reflection:'A mordomia conecta seus recursos com seus valores, sua família e seu serviço.',practice:'Escolha uma decisão financeira de hoje e relacione-a ao propósito que declarou.',prayer:'Ensina-me a administrar com fidelidade, humildade e amor.'},responsabilidad:{title:'Fidelidade no pequeno',reflection:'Um registro pequeno também conta. A clareza se constrói com hábitos simples.',practice:'Registre o próximo movimento que lembrar, mesmo que seja pequeno.',prayer:'Ajuda-me a ser fiel no pequeno sem culpa nem perfeccionismo.'},sabiduría:{title:'Buscar sabedoria antes de decidir',reflection:'A sabedoria cresce quando você observa, compara e decide com calma.',practice:application||'Revise seus números antes da próxima decisão financeira.',prayer:'Dá-me sabedoria para usar bem meus recursos e servir com liberdade.'}}
 };
 return reflections[lang][theme as keyof typeof reflections.es]??reflections[lang].sabiduría;
}

export default async function Today(){
 const context=await getContext();const {profile:p,db}=context;const month=localMonth(p.timezone);const t=copy[languageFromLocale(p.locale)];
 const [rows,categories]=await Promise.all([getTransactions(context,month),getCategories(context)]);const total=totals(rows,p.currency);
 const categoryNames=new Map(categories.map(c=>[c.id,c.name]));
 const categoryTotals=Object.entries(byCategory(rows,p.currency)).sort((a,b)=>BigInt(a[1])>BigInt(b[1])?-1:1);
 const topCategory=categoryTotals[0]?categoryNames.get(categoryTotals[0][0])??'Outros':undefined;
 const format=(minor:string)=>displayMoney(minor,p.currency,p.locale);const candidates=duplicates(rows);
 const net=BigInt(total.net.amountMinor),debt=BigInt(p.opening_debt_minor),reserve=BigInt(p.reserve_minor);
 const theme=chooseTodayPrinciple({hasRows:rows.length>0,net,debt,reserve,objective:p.objective});
 const [{data:principle},notifications]=await Promise.all([db.from('biblical_principles').select('reference,principle,application,risk_context').eq('theme',theme).eq('active',true).single(),getInternalNotifications(context,{hasRows:rows.length>0,net,reserve,debt})]);
 const action=todayAction({hasRows:rows.length>0,net,topCategory,duplicatesCount:candidates.length,objective:p.objective,locale:p.locale});
 const daily=devotional(theme,principle?.application??'',p.locale);
 return <><header className="page-heading"><p className="eyebrow">{t.eyebrow}</p><h1>{t.greeting(p.name)}</h1><p>{t.intro}</p></header>
 <InternalNotifications items={notifications} locale={p.locale}/>
 <section className="balance-panel"><span>{t.balance}</span><strong>{format(total.net.amountMinor)}</strong><p>{t.balanceHint}</p><div className="balance-details"><div>{t.income}<b>{format(total.income.amountMinor)}</b></div><div>{t.expenses}<b>{format(total.expenses.amountMinor)}</b></div></div></section>
 <section className="devotional-card"><p className="eyebrow">{t.devotional}</p><h2>{daily.title}</h2><p>{daily.reflection}</p><div><strong>{t.practice}</strong><span>{daily.practice}</span></div><div><strong>{t.prayer}</strong><span>{daily.prayer}</span></div><small>{t.devotionalNote}</small></section>
 <section className="daily-guidance"><div><p className="eyebrow">{t.actionEyebrow}</p><h2>{action}</h2><p>{topCategory?t.topCategory(topCategory):t.noPattern}</p></div>{principle&&<PrincipleCard reference={principle.reference} principle={principle.principle} application={principle.application} riskContext={principle.risk_context}/>}</section>
 <div className="page-actions"><Button asChild><Link href="/movimientos/nuevo">{t.newMovement}</Link></Button><Button asChild variant="outline"><Link href="/importar">{t.import}</Link></Button></div>
 <section className="section"><h2>{t.start}</h2><p>{t.startText}</p><dl className="metric-grid"><div><dt>{t.available}</dt><dd>{format((BigInt(p.monthly_income_minor)-BigInt(p.fixed_expenses_minor)).toString())}</dd></div><div><dt>{t.reserve}</dt><dd>{format(p.reserve_minor)}</dd></div><div><dt>{t.debt}</dt><dd>{format(p.opening_debt_minor)}</dd></div></dl></section>
 <section className="section"><p className="eyebrow">{t.detected}</p>{!rows.length?<><h2>{t.noRowsTitle}</h2><p>{t.noRowsText}</p></>:<><h2>{net<0n?t.overTitle:t.okTitle}</h2><p>{candidates.length?t.dupes(candidates.length):t.continue}</p></>}<Link href="/informe">{t.report}</Link></section></>;
}