'use client';
import {useActionState} from 'react';
import {uploadImport,mapColumns,confirmImport} from '@/app/(private)/importar/actions';
import {languageFromLocale} from '@/i18n/app';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';

function guessIndex(headers:string[],patterns:RegExp[],fallback:number){
 const found=headers.findIndex(header=>patterns.some(pattern=>pattern.test(header.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())));
 return found>=0?found:fallback;
}

const copy={
 es:{file:'Extracto CSV o XLSX',fileHint:'Hasta 1 MB y 500 movimientos. XLSX usa la primera hoja.',delimiter:'Separador CSV',comma:'Coma',semicolon:'Punto y coma',reading:'Leyendo…',prepare:'Preparar vista previa',description:'Descripción',date:'Fecha (AAAA-MM-DD)',amount:'Importe',column:'Columna ',kind:'Interpretación del importe',signed:'Positivo: ingreso · Negativo: gasto',expense:'Todos son gastos',income:'Todos son ingresos',kindHint:'Si tu banco separa cargos y abonos en columnas distintas, importa una columna por vez.',category:'Categoría inicial sugerida',categoryHint:'Podrás editar categorías después. MAYORDOMO usa esta categoría solo como punto de partida.',analyzing:'Analizando…',review:'Revisar movimientos detectados',confirmTitle:'Confirmar importación',confirmText:(count:number)=>`Se guardarán ${count} movimientos. Si algo no se ve correcto, ajusta las columnas antes de confirmar.`,confirmCheck:'Revisé fechas, importes, moneda y posibles duplicidades. Confirmo esta importación.',importing:'Importando…',confirm:'Confirmar e importar'},
 pt:{file:'Extrato CSV ou XLSX',fileHint:'Até 1 MB e 500 movimentos. XLSX usa a primeira planilha.',delimiter:'Separador CSV',comma:'Vírgula',semicolon:'Ponto e vírgula',reading:'Lendo…',prepare:'Preparar prévia',description:'Descrição',date:'Data (AAAA-MM-DD)',amount:'Valor',column:'Coluna ',kind:'Interpretação do valor',signed:'Positivo: receita · Negativo: gasto',expense:'Todos são gastos',income:'Todos são receitas',kindHint:'Se o banco separa débitos e créditos em colunas diferentes, importe uma coluna por vez.',category:'Categoria inicial sugerida',categoryHint:'Você poderá editar categorias depois. MAYORDOMO usa esta categoria só como ponto de partida.',analyzing:'Analisando…',review:'Revisar movimentos detectados',confirmTitle:'Confirmar importação',confirmText:(count:number)=>`${count} movimentos serão salvos. Se algo não parecer correto, ajuste as colunas antes de confirmar.`,confirmCheck:'Revisei datas, valores, moeda e possíveis duplicidades. Confirmo esta importação.',importing:'Importando…',confirm:'Confirmar e importar'}
};

export function UploadForm({locale='es-MX'}:{locale?:string}){const[state,action,pending]=useActionState(uploadImport,{});const t=copy[languageFromLocale(locale)];return <form action={action} className="form-stack narrow import-card"><div><Label htmlFor="file">{t.file}</Label><Input id="file" name="file" type="file" accept=".csv,.xlsx" required/><p className="hint">{t.fileHint}</p></div><div><Label htmlFor="delimiter">{t.delimiter}</Label><select id="delimiter" name="delimiter"><option value=",">{t.comma}</option><option value=";">{t.semicolon}</option></select></div>{state.error&&<p role="alert" className="error-message">{state.error}</p>}<Button disabled={pending}>{pending?t.reading:t.prepare}</Button></form>;}

export function MappingForm({id,headers,categories,locale='es-MX'}:{id:string;headers:string[];categories:{id:string;name:string}[];locale?:string}){const[state,action,pending]=useActionState(mapColumns,{});const t=copy[languageFromLocale(locale)];const defaults={description:guessIndex(headers,[/desc/,/concept/,/merchant/,/comerc/,/detalle/],0),date:guessIndex(headers,[/fecha/,/date/,/dia/],1),amount:guessIndex(headers,[/importe/,/monto/,/amount/,/valor/,/cargo/,/abono/],2)};const suggestedCategory=categories.find(c=>['Otros','Alimentación','Supermercado'].includes(c.name))?.id??categories[0]?.id;return <form action={action} className="form-stack narrow import-card"><input type="hidden" name="id" value={id}/><div className="mapping-grid">{[['description',t.description,defaults.description],['date',t.date,defaults.date],['amount',t.amount,defaults.amount]].map(([name,label,selected])=><div key={String(name)}><Label htmlFor={String(name)}>{label}</Label><select id={String(name)} name={String(name)} defaultValue={String(selected)}>{headers.map((h,i)=><option key={i} value={i}>{h||t.column+(i+1)}</option>)}</select></div>)}</div><div><Label htmlFor="kind">{t.kind}</Label><select id="kind" name="kind" defaultValue="SIGNED"><option value="SIGNED">{t.signed}</option><option value="EXPENSE">{t.expense}</option><option value="INCOME">{t.income}</option></select><p className="hint">{t.kindHint}</p></div><div><Label htmlFor="categoryId">{t.category}</Label><select id="categoryId" name="categoryId" defaultValue={suggestedCategory}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><p className="hint">{t.categoryHint}</p></div>{state.error&&<p role="alert" className="error-message">{state.error}</p>}<Button disabled={pending}>{pending?t.analyzing:t.review}</Button></form>;}

export function ConfirmImport({id,count,locale='es-MX'}:{id:string;count:number;locale?:string}){const[state,action,pending]=useActionState(confirmImport,{});const t=copy[languageFromLocale(locale)];return <form action={action} className="confirm-import-card"><input type="hidden" name="id" value={id}/><div><h2>{t.confirmTitle}</h2><p>{t.confirmText(count)}</p></div><label className="consent"><input name="confirmed" type="checkbox" required/>{t.confirmCheck}</label>{state.error&&<p role="alert" className="error-message">{state.error}</p>}<Button disabled={pending}>{pending?t.importing:t.confirm}</Button></form>;}