'use client';
import {useActionState} from 'react';
import {uploadImport,mapColumns,confirmImport} from '@/app/(private)/importar/actions';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';

function guessIndex(headers:string[],patterns:RegExp[],fallback:number){
 const found=headers.findIndex(header=>patterns.some(pattern=>pattern.test(header.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())));
 return found>=0?found:fallback;
}

export function UploadForm(){const[state,action,pending]=useActionState(uploadImport,{});return <form action={action} className="form-stack narrow import-card"><div><Label htmlFor="file">Extracto CSV o XLSX</Label><Input id="file" name="file" type="file" accept=".csv,.xlsx" required/><p className="hint">Hasta 1 MB y 500 movimientos. XLSX usa la primera hoja.</p></div><div><Label htmlFor="delimiter">Separador CSV</Label><select id="delimiter" name="delimiter"><option value=",">Coma</option><option value=";">Punto y coma</option></select></div>{state.error&&<p role="alert" className="error-message">{state.error}</p>}<Button disabled={pending}>{pending?'Leyendo…':'Preparar vista previa'}</Button></form>;}

export function MappingForm({id,headers,categories}:{id:string;headers:string[];categories:{id:string;name:string}[]}){const[state,action,pending]=useActionState(mapColumns,{});const defaults={description:guessIndex(headers,[/desc/,/concept/,/merchant/,/comerc/,/detalle/],0),date:guessIndex(headers,[/fecha/,/date/,/dia/],1),amount:guessIndex(headers,[/importe/,/monto/,/amount/,/valor/,/cargo/,/abono/],2)};const suggestedCategory=categories.find(c=>['Otros','Alimentación','Supermercado'].includes(c.name))?.id??categories[0]?.id;return <form action={action} className="form-stack narrow import-card"><input type="hidden" name="id" value={id}/><div className="mapping-grid">{[['description','Descripción',defaults.description],['date','Fecha (AAAA-MM-DD)',defaults.date],['amount','Importe',defaults.amount]].map(([name,label,selected])=><div key={String(name)}><Label htmlFor={String(name)}>{label}</Label><select id={String(name)} name={String(name)} defaultValue={String(selected)}>{headers.map((h,i)=><option key={i} value={i}>{h||'Columna '+(i+1)}</option>)}</select></div>)}</div><div><Label htmlFor="kind">Interpretación del importe</Label><select id="kind" name="kind" defaultValue="SIGNED"><option value="SIGNED">Positivo: ingreso · Negativo: gasto</option><option value="EXPENSE">Todos son gastos</option><option value="INCOME">Todos son ingresos</option></select><p className="hint">Si tu banco separa cargos y abonos en columnas distintas, importa una columna por vez.</p></div><div><Label htmlFor="categoryId">Categoría inicial sugerida</Label><select id="categoryId" name="categoryId" defaultValue={suggestedCategory}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><p className="hint">Podrás editar categorías después. MAYORDOMO usa esta categoría solo como punto de partida.</p></div>{state.error&&<p role="alert" className="error-message">{state.error}</p>}<Button disabled={pending}>{pending?'Analizando…':'Revisar movimientos detectados'}</Button></form>;}

export function ConfirmImport({id,count}:{id:string;count:number}){const[state,action,pending]=useActionState(confirmImport,{});return <form action={action} className="confirm-import-card"><input type="hidden" name="id" value={id}/><div><h2>Confirmar importación</h2><p>Se guardarán {count} movimientos. Si algo no se ve correcto, ajusta las columnas antes de confirmar.</p></div><label className="consent"><input name="confirmed" type="checkbox" required/>Revisé fechas, importes, moneda y posibles duplicidades. Confirmo esta importación.</label>{state.error&&<p role="alert" className="error-message">{state.error}</p>}<Button disabled={pending}>{pending?'Importando…':'Confirmar e importar'}</Button></form>;}
